# Generated by Django 4.0.2 on 2022-02-25 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('departure_address', models.CharField(max_length=255)),
                ('destination_address', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('OPEN', 'OPEN'), ('PENDING', 'PENDING'), ('DELIVERED', 'DELIVERED')], default='DRAFT', max_length=255)),
            ],
        ),
    ]
